#!/usr/bin/env ruby

$: << File.expand_path("../lib", __FILE__)
require 'go2nix'
require 'json'

require 'fileutils'
FileUtils.mkdir("dump")
# run
# til = DateTime.iso8601("2014-05-03T00:00:00Z")
til = nil
# pkg = ["github.com/mitchellh/packer"]
# pkg = ["code.google.com/p/google-api-go-client"]
pkg = ["launchpad.net/tomb"]
revs = Go2nix.snapshot("dump", til, pkg)
revs = revs.map(&:as_json)
json = JSON.pretty_generate(revs)
puts json
